### ISSUE TITLE
Добавить поле наличия

### ISSUE THREAD

**Issue by mar294** [akochnov/egafood#10]
Лёх, в списке товаров не видно наличие (только в карточке). А заказать можно, что не логично. Надо, чтобы было видно "нет в наличии", либо серым текст и затуманенную фотку. Чё проще.

**Comment by mar294** [comment]
Хорошо бы сделать, чтобы можно было выбирать сразу количество добавляемого в корзину товара, не заходя в карточку.

**Comment by akochnov** [comment]
Прикрутил форму для ввода количества продуктов, добавляемых в корзину:
http://puu.sh/h3Ylr/6d6d8487f3.png

"нет в наличии" добавлю завтра

**Comment by mar294** [comment]
Лёх, а в каком файле это живёт, я бы падинги поправил

**Comment by akochnov** [comment]
http://puu.sh/h4zYO/b2ac2354fb.png

**Comment by akochnov** [comment]
ИНформация о наличии теперь есть на страницах с категориями
http://puu.sh/h4COg/5ce2dd207f.png
