### ISSUE TITLE
Перемотка страницы

### ISSUE THREAD

**Issue by mar294** [akochnov/egafood#11]
Ещё одно неудобство связано с обновлением страницы и возвратом в топ, когда нажимаешь кнопку "купить" в списке. Каждый раз страница перескакивает вверх, что особенно неудобно с длинными списками или с мобилы. Можешь посмотреть как исправить?

**Comment by akochnov** [comment]
Убрал перемотку страницы, изучаю чем ее заменить, думаю сделать попап самоисчезающий.
Если есть мысли - напиши.

**Comment by mar294** [comment]
Не знаю, сейчас даже на цсс можно какую-то херь элементарную сделать с движением или фэйдом и т.д. В jq наверное есть что-нибудь. Хотя бы просто чтоб мигнуло беленьким, или галочка в кружочке бледная появилась и исчезла за секунду. Галочку могу скинуть.

**Comment by akochnov** [comment]
захуярил, тестируй

![image](https://cloud.githubusercontent.com/assets/9281874/7118011/2983312c-e205-11e4-8d82-e63a28b9686d.png)

**Comment by mar294** [comment]
Есть невозврат:
![screen shot 2015-04-13 at 17 56 12](https://cloud.githubusercontent.com/assets/10448283/7118328/15186598-e207-11e4-8135-e95396486cbe.png)
![screen shot 2015-04-13 at 17 56 07](https://cloud.githubusercontent.com/assets/10448283/7118329/1520cb66-e207-11e4-8393-a70ce361bf1c.png)

**Comment by mar294** [comment]
Примеры добавления в корзину:
http://svinopas-ru.ru/index.php?route=product/category&path=20_27
http://cow-boys.ru/shop/govyadina/
Нашёл пока тока два типа, в основном у всех фотка улетает, но мне лично не очень нравится. 
У коровомальчиков смысл тот, что нужно.

**Comment by akochnov** [comment]
Готово
