### ISSUE TITLE
Добавить сортировку по наличию

### ISSUE THREAD

**Issue by mar294** [akochnov/egafood#12]
Лёха, логично иметь сортировку товара по наличию. Сортировку по модели можно убрать за ненадобностью.

**Comment by mar294** [comment]
![screen shot 2015-04-07 at 14 23 31](https://cloud.githubusercontent.com/assets/10448283/7022167/ba927b9c-dd31-11e4-840a-e70a4e198a39.png)

**Comment by akochnov** [comment]
Готово
http://puu.sh/h5akU/0381a09459.png
дефолтная сортировка по названию по возрастанию
все товары с 0 остатком - в конце списка, отсортированые по тому же правилу.
Сортировку по модели - грохнул

Проверяй.
