### ISSUE TITLE
Добавить поле для весового товара

### ISSUE THREAD

**Issue by mar294** [akochnov/egafood#14]
Добавить поле для весового товара "цена указана за 1кг" маленькими буковками.

**Comment by akochnov** [comment]
Готово, выполнил как мы обговаривали в вотсапе с разным родом числительного:

![image](https://cloud.githubusercontent.com/assets/9281874/8745274/d1fd6680-2c86-11e5-926c-770cb96637ce.png)
![image](https://cloud.githubusercontent.com/assets/9281874/8745278/e1ca03ac-2c86-11e5-82ec-daaf16cf9372.png)

поменять фразировку можно в product.tpl строки 35-44

![image](https://cloud.githubusercontent.com/assets/9281874/8745305/27886dac-2c87-11e5-85bb-71343ebaa58c.png)
