### ISSUE TITLE
Проблема с отзывами товара

### ISSUE THREAD

**Issue by mar294** [akochnov/egafood#17]
Заметили странную вещь:
Колян поснимал галки с ненужных для продажи товаров, чтобы они не выгружались на сайт, изменения при этом на сайте не произошли. Для того, чтобы это случилось, приходится каждый раз нажимать галки в админке "сбрасывать товары, категории, количество", загружать, а потом снимать галки и ещё раз загружать, что не удобно. При этом, отзыв о твороге 0,5 съехал в говяжьи почки, а потом, когда Колян отменил для выгрузки и почки, отзыв уехал в студень........ В итоге я его удалил из админки, чтоб не бесил.

**Comment by mar294** [comment]
Картинки тоже нахуй слетели все....................... Я больше не перенесу их руками добавлять.

**Comment by mar294** [comment]
Ещё заметил, что в статье про молоко рекомендуемым товаром стала баранья шея, а не молоко пастеризованное ёж

**Comment by mar294** [comment]
Нужно попробовать восстановить отзывы, хотя бы текст и автора

**Comment by akochnov** [comment]
VALUES (3,4,0,18,'Елена Лаврикова','Добрый день! Продукцию ЁGAFOOD покупаю около года, всегда очень довольна молочными продуктами и большим ассортиментом готовых изделий - пельмени, тефтели, блинчики, сыр адыгейский! Зайдя на сайт сегодня, была приятно удивленна, что можно приобрести еще и ОВОЩИ! По фото видно, что это действительно заботливо ухоженный домашний огород! Очень рада! Делаю заказы! СПАСИБО! ',5,0,'0000',1,'2015-07-25 18:12:59','0000-00-00 00:00:00'),(4,1,0,25,'Сергей Геллер','[size=100] Друзья!!!!\r\n\r\nХочу просто сказать огромное спасибо всей команде ЁгаФуд за прекрасную, вкусную и ЗДОРОВУЮ еду. Я с вами уже год и ни разу не пожалел, что стал вашим постонным клиентом.\r\nРадует, что ассортимент пополняется - это значит,что компания растет и при этом не теряет качество, что немаловажно в\r\nсовременном мире. \r\nЯ с удовольствием вас рекомендую всем моим друзьям и так же уже получил от них лестные отзывы – за вас никогда еще не было стыдно)))\r\nТак держать!!!!! Процветайте и радуйте нас своей КАЧЕСТВЕННОЙ продукцией!!!! \r\nСпасибо[/size]',5,0,'0000',1,'2015-07-27 15:30:09','0000-00-00 00:00:00');
