### ISSUE TITLE
Прописать фотку "no photo"

### ISSUE THREAD

**Issue by mar294** [akochnov/egafood#18]
для товара, у которого нет фотографии, пока не появится.

**Comment by akochnov** [comment]
Прописал фотку /image/no_image.jpg в категории и в карточке товара.
Отображается в категории как при виде "сетка" так и при виде "список"

**Comment by mar294** [comment]
переписал на другую /image/cache/data/a_logo-v5dark_bw-100x100.png

**Comment by akochnov** [comment]
Добавил фотку так же в "Рекомендуемые"
