### ISSUE TITLE
Поле упаковка

### ISSUE THREAD

**Issue by akochnov** [akochnov/egafood#3]
добавить поле “упаковка” с содержанием вроде “расфасовано в бутылки по 0,33мл” или “расфасовано примерно по 0,7кг” в зависимости от товара

**Comment by akochnov** [comment]
Можно использовать "описание товара"
http://puu.sh/fxFh5/783d0d609f.png

**Comment by akochnov** [comment]
![image](https://cloud.githubusercontent.com/assets/9281874/6076826/5b3783c0-adf9-11e4-86e7-d6537f30f45a.png)

**Comment by akochnov** [comment]
Все окей, но нужно сместить блок "описание" вверх на странице товара

![image](https://cloud.githubusercontent.com/assets/9281874/6076846/97e5ef78-adf9-11e4-9acc-b4427043df8d.png)

**Comment by mar294** [comment]
Можно (например) заменить атрибут "модель:" на "расфасовано по:" и вручную прописывать в админке "0,7 кг" или "200-300 г".

**Comment by akochnov** [comment]
я посмотрел описания модуля обмена данными
там есть информация, что атрибуты тоже выгружаются
можно дать добро на доработку 1с, а я потом с этими данными разберусь уже в магазине

**Comment by mar294** [comment]
Повзони Владимиру Дмитриевичу

**Comment by mar294** [comment]
Дмитрич добавил такое поле в базе. Я заполнил пробно в говяжьей вырезке.

**Comment by akochnov** [comment]
Вот как сделано:
![image](https://cloud.githubusercontent.com/assets/9281874/6846501/fa490636-d3cf-11e4-8213-025cd0d52024.png)

Вот как надо:
![image](https://cloud.githubusercontent.com/assets/9281874/6846584/4da9f718-d3d0-11e4-9bd1-f11f7de70587.png)

![image](https://cloud.githubusercontent.com/assets/9281874/6846603/73775d3c-d3d0-11e4-9f67-dad7476b7c54.png)

**Comment by akochnov** [comment]
Леха, победил.
Нашел баг в модуле обмена opencart - неправильно парсилась загрузка свойств. Устранил проблему
http://puu.sh/h7iB8/7d9f345481.png

Полагаю ты теперь захочешь изменить отображение этого аттрибута на странице товара?

**Comment by akochnov** [comment]
Добавил вывод аттрибутов повыше
![image](https://cloud.githubusercontent.com/assets/9281874/7076437/15f8d7a6-df12-11e4-92c9-5482229599ac.png)
