### ISSUE TITLE
вместо этого добавить карту сайта

### ISSUE THREAD

**Issue by akochnov** [akochnov/egafood#4]

**Comment by akochnov** [comment]
Марыч, нарисуй карту со всеми категориями

**Comment by mar294** [comment]
![karta](https://cloud.githubusercontent.com/assets/10448283/6210325/8995e354-b5df-11e4-80ec-09a6cfdcf473.png)
Добавить категории товаров, а также новости и статьи в информацию.

**Comment by akochnov** [comment]
готово
http://puu.sh/g3vTn/8f2ac76f01.png
