### ISSUE TITLE
Модуль simple - лишние поля

### ISSUE THREAD

**Issue by mar294** [akochnov/egafood#8]
Лёх, у меня чё-то модуль сейчас затребовал при доставке индекс!!! Не помню, просил ли я тебя его убрать.

**Comment by akochnov** [comment]
убрал
http://puu.sh/gs3QU/7cabd66fd1.png

**Comment by mar294** [comment]
![Uploading Screen Shot 2015-03-08 at 23.09.09.png . . .]()

**Comment by mar294** [comment]
![screen shot 2015-03-08 at 23 09 09](https://cloud.githubusercontent.com/assets/10448283/6547422/cd260ac2-c5e8-11e4-9fdd-2bdc09d69785.png)

**Comment by akochnov** [comment]
пофиксил здесь тоже - проверь
![image](https://cloud.githubusercontent.com/assets/9281874/6547723/9dc27b54-c5f1-11e4-9266-7040030b67b4.png)

**Comment by mar294** [comment]
Лёх, ещё одну хуйню забыл очевидную...  Имя то с Фамилией нахуй заново указывать?

**Comment by akochnov** [comment]
логично, убрал.

Ты мне тогда объясни что за хуйня - адрес оплаты?)))

**Comment by mar294** [comment]
бля, да хуй их знает.... типа доставки чё-нить. Типа если платишь на месте, то совпадает с адресом доставки

**Comment by akochnov** [comment]
закрываем ишью?
